### ISSUE TITLE
Configure step of bundled fltk fails on Windows due to missing X11 libraries

### ISSUE THREAD

**Issue by jputcu** [deech/fltkhs#74]
On Windows the configuration of the bundled fltk library fails saying it is missing the X11 libraries, which we don't need.
It appears my build platform isn't detected correctly.
By passing the flag `--build=mingw32` to the fltk configure step it builds correctly.
I'm using `msys2` for the build environment.
See related discussion: https://groups.google.com/forum/#!topic/fltkgeneral/sHq2LeoXRfI

**Comment by deech** [comment]
I'm not sure how this and your [previous issue](https://github.com/deech/fltkhs/issues/73) are happening. I'm on Windows 10 and I just pulled and installed from Git without an issue.

But yes, thanks for linking that discussion, I'll add `build=mingw32` to the configure step.

**Comment by deech** [comment]
Another difference might be that I'm invoking my `msys2` prompt with `stack exec mintty`.

**Comment by jputcu** [comment]
Your way also works for me.

**Comment by deech** [comment]
I pushed up a fix that adds `build=mingw32`. If it works would you mind closing this and the previous issue?

**Comment by jputcu** [comment]
The previous issue relates to a functions which doesn't exist in the fltk library, so that isn't fixed yet

**Comment by jputcu** [comment]
Also note that this solution is 32-bit specific!

**Comment by deech** [comment]
Ooh, sorry. I'll remove it.

**Comment by jputcu** [comment]
Using the `stack exec mintty` environment was the documented way to install and works, so closing.
